questions = {
    1: {
        'question': 'Хто написав "Гаррі Поттера"?',
        'correct_ans': 'Джоан Роулінг',
        'wrong_ans1': 'Дж. Р. Р. Толкін',
        'wrong_ans2': 'Стівен Кінг',
        'wrong_ans3': 'Агата Крісті',
    },
    2: {
        'question': 'Яка планета найближча до Сонця?',
        'correct_ans': 'Меркурій',
        'wrong_ans1': 'Венера',
        'wrong_ans2': 'Земля',
        'wrong_ans3': 'Марс',
    },
    3: {
        'question': 'Скільки континентів на Землі?',
        'correct_ans': '7',
        'wrong_ans1': '5',
        'wrong_ans2': '6',
        'wrong_ans3': '8',
    },
    4: {
        'question': 'Яка ріка є найдовшою у світі?',
        'correct_ans': 'Ніл',
        'wrong_ans1': 'Амазонка',
        'wrong_ans2': 'Янцзи',
        'wrong_ans3': 'Міссісіпі',
    },
    5: {
        'question': 'Коли відбулася перша людина на Місяці?',
        'correct_ans': '1969',
        'wrong_ans1': '1965',
        'wrong_ans2': '1972',
        'wrong_ans3': '1980',
    },
    6: {
        'question': 'Яка мова є офіційною в Бразилії?',
        'correct_ans': 'Португальська',
        'wrong_ans1': 'Іспанська',
        'wrong_ans2': 'Англійська',
        'wrong_ans3': 'Французька',
    },
    7: {
        'question': 'Скільки днів у високосному році?',
        'correct_ans': '366',
        'wrong_ans1': '365',
        'wrong_ans2': '364',
        'wrong_ans3': '367',
    },
}
